#!/usr/bin/env ansible-playbook
---
- name: push role to galaxy
  hosts: localhost
  become: false
  gather_facts: false
  gather_subset:
    - min

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  tasks:
    - name: set role_path and role_name
      set_fact:
        role_path: "{{ lookup('env', 'PWD') }}"
        role_name: "{{ lookup('env', 'PWD') | basename | regex_replace('ansible-role-') }}"

    - name: push tags to github
      shell: "set -o pipefail ; git push --tags"
      changed_when: false
      failed_when: false

    - name: push to galaxy
      shell: "set -o pipefail ; ansible-galaxy role import --api-key {{ GALAXY_API_KEY }} {{ galaxy_namespace }} ansible-role-{{ role_name }}"
      register: galaxy_push
      changed_when: false
      failed_when: false
