#!/usr/bin/env ansible-playbook
---
- name: move_to_collections
  hosts: localhost
  become: false
  gather_facts: true
  gather_subset:
    - min

  vars_files:
    - vars/main.yml

  tasks:
    - name: set role_path and role_name
      set_fact:
        role_path: "{{ lookup('env', 'PWD') }}"
        role_name: "{{ lookup('env', 'PWD') | basename | regex_replace('ansible-role-') }}"

    - name: move_to_collections
      shell: "set -o pipefail ; ../move_to_collections/transform.sh"
      register: transformed
      changed_when: false
      failed_when: false
