---
name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: "${{ secrets.SLACK_WEBHOOK_URL }}"
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: "#ansible"
          message: Starting buluma.testing GitLab Trigger...
        if: always()
      - uses: actions/checkout@v2.4.0
      - name: Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "buluma/ansible-role-testing"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "buluma"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: "33844960"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: "${{ job.status }}"
          steps: "${{ toJson(steps) }}"
          channel: "#ansible"
        if: always()
